HELP = r'''
I can help you with your math operations\! Look at the commands below to get more information\.

*LINEAR ALGEBRA*
/matrices \- matrices operations
/vectors \- vectors operations
/plane \- plane operations

*BOT INFORMATION*
Creator: Dylan Tintenfich
GitHub: [PyMath](https://github.com/dylannalex/PyMath.git)
'''

VECTOR_COMMANDS = r'''
_*VECTORS OPERATIONS*_

*INFO:*
Operate with vectors

*OPERATIONS:*
_Dot product:_
dot vec\(a b c\) vec\(d e f\)

_Cross product:_
cross vec\(a b c\) vec\(d e f\)

_Angle between vectors:_
angle vec\(a b c\) vec\(d e f\)
'''

PLANES_COMMANDS = r'''
_*PLANE OPERATIONS*_

*INFO:*
Get plane equation with inputted data \(vectors, normal vectors, points\)

*OPERATIONS:*
_Plane generated by 2 vectors and a point:_
plane vec\(a b c\) vec\(d e f\) pt\(h i j\)

_Plane with normal vector and plane's point:_
plane nvec\(a b c\) pt\(d e f\)

_Plane containing 3 points:_
plane pt\(a b c\) pt\(d e f\) pt\(h i j\)
'''

MATRICES_COMMANDS = r'''
_*MATRICES OPERATIONS*_

*INFO:*
Operate with matrices

*MATRIX SINTAX:*
matrix\[a b, c d\]

_Examples:_
\[a b c\] \-\-\-\> matrix\[a b c, d e f\]
\[d e f\]  

\[a b\] 
\[c d\]  \-\-\-\> matrix\[a b, c d, e f\]
\[e f\]

*OPERATIONS:*
_Determinant:_
det matrix\[a b, c d\]

_Matrix inverse:_
inverse matrix\[a b, c d\]

_Matrix multiplication:_
matmul matrix\[a b, c d, e f\] matrix\[g h i, j k l\]

_Matrix addition:_
matsum matrix\[a b, c d\] matrix\[e f, g h\]

_Eigen values:_
eigenvals matrix\[a b, c d\]
'''
